version: '3.8'

services:
 db:
  image: mysql:8.0.29
  environment:
   MYSQL_ROOT_PASSWORD: docker
   MYSQL_DATABASE: clients
   MYSQL_USER: root
   MYSQL_PASSWORD: docker
   ports:
    -"3306:3306"
   volumes:
    -db_data:/var/lib/mysql
    
volumes:
 db_data: